//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseholdMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HouseholdMS.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✖ Cancel.
        /// </summary>
        public static string AHC_Btn_Cancel {
            get {
                return ResourceManager.GetString("AHC_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑 Delete.
        /// </summary>
        public static string AHC_Btn_Delete {
            get {
                return ResourceManager.GetString("AHC_Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💾 Save.
        /// </summary>
        public static string AHC_Btn_Save {
            get {
                return ResourceManager.GetString("AHC_Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string AHC_FieldRequired {
            get {
                return ResourceManager.GetString("AHC_FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is set to Out of Service. Please add a short note describing the reason and consider opening a Service Call from the dashboard..
        /// </summary>
        public static string AHC_Info_OutOfService {
            get {
                return ResourceManager.GetString("AHC_Info_OutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string AHC_Label_ContactNumber {
            get {
                return ResourceManager.GetString("AHC_Label_ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string AHC_Label_District {
            get {
                return ResourceManager.GetString("AHC_Label_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Date.
        /// </summary>
        public static string AHC_Label_InstallDate {
            get {
                return ResourceManager.GetString("AHC_Label_InstallDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Inspection Date.
        /// </summary>
        public static string AHC_Label_LastInspectDate {
            get {
                return ResourceManager.GetString("AHC_Label_LastInspectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        public static string AHC_Label_Municipality {
            get {
                return ResourceManager.GetString("AHC_Label_Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note (optional).
        /// </summary>
        public static string AHC_Label_NoteOptional {
            get {
                return ResourceManager.GetString("AHC_Label_NoteOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string AHC_Label_OwnerName {
            get {
                return ResourceManager.GetString("AHC_Label_OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AHC_Label_Status {
            get {
                return ResourceManager.GetString("AHC_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string AHC_Label_UserName {
            get {
                return ResourceManager.GetString("AHC_Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service records yet..
        /// </summary>
        public static string AHC_ServiceHistory_Empty {
            get {
                return ResourceManager.GetString("AHC_ServiceHistory_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛠 Service History.
        /// </summary>
        public static string AHC_ServiceHistory_Title {
            get {
                return ResourceManager.GetString("AHC_ServiceHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 records.
        /// </summary>
        public static string AHC_ServiceHistory_Zero {
            get {
                return ResourceManager.GetString("AHC_ServiceHistory_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AHC_SH_Col_Date {
            get {
                return ResourceManager.GetString("AHC_SH_Col_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string AHC_SH_Col_Id {
            get {
                return ResourceManager.GetString("AHC_SH_Col_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AHC_SH_Col_Status {
            get {
                return ResourceManager.GetString("AHC_SH_Col_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string AHC_SH_Col_Summary {
            get {
                return ResourceManager.GetString("AHC_SH_Col_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string AHC_SH_Col_Technician {
            get {
                return ResourceManager.GetString("AHC_SH_Col_Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Add Household.
        /// </summary>
        public static string AHV_AddHousehold {
            get {
                return ResourceManager.GetString("AHV_AddHousehold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string AHV_Column_Comment {
            get {
                return ResourceManager.GetString("AHV_Column_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string AHV_Column_Contact {
            get {
                return ResourceManager.GetString("AHV_Column_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string AHV_Column_District {
            get {
                return ResourceManager.GetString("AHV_Column_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string AHV_Column_ID {
            get {
                return ResourceManager.GetString("AHV_Column_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string AHV_Column_Installed {
            get {
                return ResourceManager.GetString("AHV_Column_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Inspect.
        /// </summary>
        public static string AHV_Column_LastInspect {
            get {
                return ResourceManager.GetString("AHV_Column_LastInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        public static string AHV_Column_Municipality {
            get {
                return ResourceManager.GetString("AHV_Column_Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string AHV_Column_OwnerName {
            get {
                return ResourceManager.GetString("AHV_Column_OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AHV_Column_Status {
            get {
                return ResourceManager.GetString("AHV_Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string AHV_Column_UserName {
            get {
                return ResourceManager.GetString("AHV_Column_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No households found.
        /// </summary>
        public static string AHV_EmptyState {
            get {
                return ResourceManager.GetString("AHV_EmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        public static string AHV_RO_Comment {
            get {
                return ResourceManager.GetString("AHV_RO_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string AHV_RO_Contact {
            get {
                return ResourceManager.GetString("AHV_RO_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District:.
        /// </summary>
        public static string AHV_RO_District {
            get {
                return ResourceManager.GetString("AHV_RO_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed:.
        /// </summary>
        public static string AHV_RO_Installed {
            get {
                return ResourceManager.GetString("AHV_RO_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Inspect:.
        /// </summary>
        public static string AHV_RO_LastInspect {
            get {
                return ResourceManager.GetString("AHV_RO_LastInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality:.
        /// </summary>
        public static string AHV_RO_Municipality {
            get {
                return ResourceManager.GetString("AHV_RO_Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name:.
        /// </summary>
        public static string AHV_RO_OwnerName {
            get {
                return ResourceManager.GetString("AHV_RO_OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string AHV_RO_Status {
            get {
                return ResourceManager.GetString("AHV_RO_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name:.
        /// </summary>
        public static string AHV_RO_UserName {
            get {
                return ResourceManager.GetString("AHV_RO_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by owner, user, area or contact.
        /// </summary>
        public static string AHV_SearchPlaceholder {
            get {
                return ResourceManager.GetString("AHV_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is read-only in this view. Change it in the Service/Status view..
        /// </summary>
        public static string AHV_Status_Tooltip {
            get {
                return ResourceManager.GetString("AHV_Status_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✖ Cancel.
        /// </summary>
        public static string AIC_Btn_Cancel {
            get {
                return ResourceManager.GetString("AIC_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑 Delete.
        /// </summary>
        public static string AIC_Btn_Delete {
            get {
                return ResourceManager.GetString("AIC_Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✔ Save Changes.
        /// </summary>
        public static string AIC_Btn_Save {
            get {
                return ResourceManager.GetString("AIC_Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage inventory item.
        /// </summary>
        public static string AIC_Header_Subtitle {
            get {
                return ResourceManager.GetString("AIC_Header_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is low on stock..
        /// </summary>
        public static string AIC_Info_LowStock {
            get {
                return ResourceManager.GetString("AIC_Info_LowStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is out of stock..
        /// </summary>
        public static string AIC_Info_OutOfStock {
            get {
                return ResourceManager.GetString("AIC_Info_OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Quantity.
        /// </summary>
        public static string AIC_Label_InitialQty {
            get {
                return ResourceManager.GetString("AIC_Label_InitialQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string AIC_Label_ItemType {
            get {
                return ResourceManager.GetString("AIC_Label_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note (optional).
        /// </summary>
        public static string AIC_Label_NoteOptional {
            get {
                return ResourceManager.GetString("AIC_Label_NoteOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Stock Threshold.
        /// </summary>
        public static string AIC_Label_Threshold {
            get {
                return ResourceManager.GetString("AIC_Label_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restock History.
        /// </summary>
        public static string AIC_RestockHistory_Title {
            get {
                return ResourceManager.GetString("AIC_RestockHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string AIC_RH_Col_By {
            get {
                return ResourceManager.GetString("AIC_RH_Col_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string AIC_RH_Col_Note {
            get {
                return ResourceManager.GetString("AIC_RH_Col_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string AIC_RH_Col_Qty {
            get {
                return ResourceManager.GetString("AIC_RH_Col_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string AIC_RH_Col_When {
            get {
                return ResourceManager.GetString("AIC_RH_Col_When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string AIC_Snapshot_Available {
            get {
                return ResourceManager.GetString("AIC_Snapshot_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Restocked.
        /// </summary>
        public static string AIC_Snapshot_LastRestocked {
            get {
                return ResourceManager.GetString("AIC_Snapshot_LastRestocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Used.
        /// </summary>
        public static string AIC_Snapshot_LastUsed {
            get {
                return ResourceManager.GetString("AIC_Snapshot_LastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Snapshot.
        /// </summary>
        public static string AIC_Snapshot_Title {
            get {
                return ResourceManager.GetString("AIC_Snapshot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string AIC_Snapshot_Used {
            get {
                return ResourceManager.GetString("AIC_Snapshot_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Stock.
        /// </summary>
        public static string AIC_Status_InStock {
            get {
                return ResourceManager.GetString("AIC_Status_InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Stock.
        /// </summary>
        public static string AIC_Status_LowStock {
            get {
                return ResourceManager.GetString("AIC_Status_LowStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Stock.
        /// </summary>
        public static string AIC_Status_OutOfStock {
            get {
                return ResourceManager.GetString("AIC_Status_OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Used.
        /// </summary>
        public static string AIC_UH_Col_QtyUsed {
            get {
                return ResourceManager.GetString("AIC_UH_Col_QtyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string AIC_UH_Col_Service {
            get {
                return ResourceManager.GetString("AIC_UH_Col_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician(s).
        /// </summary>
        public static string AIC_UH_Col_Technicians {
            get {
                return ResourceManager.GetString("AIC_UH_Col_Technicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used By.
        /// </summary>
        public static string AIC_UH_Col_UsedBy {
            get {
                return ResourceManager.GetString("AIC_UH_Col_UsedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string AIC_UH_Col_When {
            get {
                return ResourceManager.GetString("AIC_UH_Col_When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage History.
        /// </summary>
        public static string AIC_UsageHistory_Title {
            get {
                return ResourceManager.GetString("AIC_UsageHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV Testing Workbench.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✖ Cancel.
        /// </summary>
        public static string AS_Cancel {
            get {
                return ResourceManager.GetString("AS_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✔ Confirm Service.
        /// </summary>
        public static string AS_Confirm {
            get {
                return ResourceManager.GetString("AS_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string AS_FieldRequired {
            get {
                return ResourceManager.GetString("AS_FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Service Call.
        /// </summary>
        public static string AS_Header {
            get {
                return ResourceManager.GetString("AS_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem description (optional).
        /// </summary>
        public static string AS_Problem_Label {
            get {
                return ResourceManager.GetString("AS_Problem_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string AS_Summary_Contact {
            get {
                return ResourceManager.GetString("AS_Summary_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District:.
        /// </summary>
        public static string AS_Summary_District {
            get {
                return ResourceManager.GetString("AS_Summary_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household ID:.
        /// </summary>
        public static string AS_Summary_HouseholdID {
            get {
                return ResourceManager.GetString("AS_Summary_HouseholdID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality:.
        /// </summary>
        public static string AS_Summary_Municipality {
            get {
                return ResourceManager.GetString("AS_Summary_Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner:.
        /// </summary>
        public static string AS_Summary_Owner {
            get {
                return ResourceManager.GetString("AS_Summary_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string AS_Summary_Status {
            get {
                return ResourceManager.GetString("AS_Summary_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household summary.
        /// </summary>
        public static string AS_Summary_Title {
            get {
                return ResourceManager.GetString("AS_Summary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string AS_Summary_User {
            get {
                return ResourceManager.GetString("AS_Summary_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✖ Close.
        /// </summary>
        public static string ASRC_Btn_Close {
            get {
                return ResourceManager.GetString("ASRC_Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑 Delete.
        /// </summary>
        public static string ASRC_Btn_Delete {
            get {
                return ResourceManager.GetString("ASRC_Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✔ Save.
        /// </summary>
        public static string ASRC_Btn_Save {
            get {
                return ResourceManager.GetString("ASRC_Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:.
        /// </summary>
        public static string ASRC_Det_Action {
            get {
                return ResourceManager.GetString("ASRC_Det_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished:.
        /// </summary>
        public static string ASRC_Det_Finished {
            get {
                return ResourceManager.GetString("ASRC_Det_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household:.
        /// </summary>
        public static string ASRC_Det_Household {
            get {
                return ResourceManager.GetString("ASRC_Det_Household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Used:.
        /// </summary>
        public static string ASRC_Det_Inventory {
            get {
                return ResourceManager.GetString("ASRC_Det_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem:.
        /// </summary>
        public static string ASRC_Det_Problem {
            get {
                return ResourceManager.GetString("ASRC_Det_Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service ID:.
        /// </summary>
        public static string ASRC_Det_ServiceId {
            get {
                return ResourceManager.GetString("ASRC_Det_ServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started:.
        /// </summary>
        public static string ASRC_Det_Started {
            get {
                return ResourceManager.GetString("ASRC_Det_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technicians:.
        /// </summary>
        public static string ASRC_Det_Technicians {
            get {
                return ResourceManager.GetString("ASRC_Det_Technicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Taken.
        /// </summary>
        public static string ASRC_Form_ActionTaken {
            get {
                return ResourceManager.GetString("ASRC_Form_ActionTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household ID.
        /// </summary>
        public static string ASRC_Form_HouseholdID {
            get {
                return ResourceManager.GetString("ASRC_Form_HouseholdID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Inspect Date.
        /// </summary>
        public static string ASRC_Form_LastInspectDate {
            get {
                return ResourceManager.GetString("ASRC_Form_LastInspectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        public static string ASRC_Form_Problem {
            get {
                return ResourceManager.GetString("ASRC_Form_Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Date.
        /// </summary>
        public static string ASRC_Form_RepairDate {
            get {
                return ResourceManager.GetString("ASRC_Form_RepairDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician ID.
        /// </summary>
        public static string ASRC_Form_TechnicianID {
            get {
                return ResourceManager.GetString("ASRC_Form_TechnicianID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service details and activity.
        /// </summary>
        public static string ASRC_Header_Subtitle {
            get {
                return ResourceManager.GetString("ASRC_Header_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Add Service Record.
        /// </summary>
        public static string ASRC_Header_Title {
            get {
                return ResourceManager.GetString("ASRC_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string ASRC_Status_Canceled {
            get {
                return ResourceManager.GetString("ASRC_Status_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string ASRC_Status_Finished {
            get {
                return ResourceManager.GetString("ASRC_Status_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ASRC_Status_Open {
            get {
                return ResourceManager.GetString("ASRC_Status_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational.
        /// </summary>
        public static string Common_Status_Operational {
            get {
                return ResourceManager.GetString("Common_Status_Operational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Service.
        /// </summary>
        public static string Common_Status_OutOfService {
            get {
                return ResourceManager.GetString("Common_Status_OutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dash_Header {
            get {
                return ResourceManager.GetString("Dash_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open List.
        /// </summary>
        public static string Dash_OpenList {
            get {
                return ResourceManager.GetString("Dash_OpenList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational.
        /// </summary>
        public static string Dash_Operational {
            get {
                return ResourceManager.GetString("Dash_Operational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Service.
        /// </summary>
        public static string Dash_OutOfService {
            get {
                return ResourceManager.GetString("Dash_OutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Dash_Remaining {
            get {
                return ResourceManager.GetString("Dash_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restocked.
        /// </summary>
        public static string Dash_Restocked_Label {
            get {
                return ResourceManager.GetString("Dash_Restocked_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏠 Household.
        /// </summary>
        public static string Dash_Section_Household {
            get {
                return ResourceManager.GetString("Dash_Section_Household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📦 Inventory.
        /// </summary>
        public static string Dash_Section_Inventory {
            get {
                return ResourceManager.GetString("Dash_Section_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOW.
        /// </summary>
        public static string Dash_Status_Low {
            get {
                return ResourceManager.GetString("Dash_Status_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Dash_Status_Ok {
            get {
                return ResourceManager.GetString("Dash_Status_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT.
        /// </summary>
        public static string Dash_Status_Out {
            get {
                return ResourceManager.GetString("Dash_Status_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        public static string Dash_Threshold_Label {
            get {
                return ResourceManager.GetString("Dash_Threshold_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Households.
        /// </summary>
        public static string Dash_TotalHouseholds {
            get {
                return ResourceManager.GetString("Dash_TotalHouseholds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Sections.
        /// </summary>
        public static string Dashboard_Sections {
            get {
                return ResourceManager.GetString("Dashboard_Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restock.
        /// </summary>
        public static string Inv_Action_Restock {
            get {
                return ResourceManager.GetString("Inv_Action_Restock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Inv_Action_Use {
            get {
                return ResourceManager.GetString("Inv_Action_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Qty.
        /// </summary>
        public static string Inv_Column_AvailableQty {
            get {
                return ResourceManager.GetString("Inv_Column_AvailableQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Inv_Column_ID {
            get {
                return ResourceManager.GetString("Inv_Column_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string Inv_Column_ItemType {
            get {
                return ResourceManager.GetString("Inv_Column_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Restocked.
        /// </summary>
        public static string Inv_Column_LastRestocked {
            get {
                return ResourceManager.GetString("Inv_Column_LastRestocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Threshold.
        /// </summary>
        public static string Inv_Column_LowThreshold {
            get {
                return ResourceManager.GetString("Inv_Column_LowThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Inv_Column_Note {
            get {
                return ResourceManager.GetString("Inv_Column_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Qty.
        /// </summary>
        public static string Inv_Column_UsedQty {
            get {
                return ResourceManager.GetString("Inv_Column_UsedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Quantity:.
        /// </summary>
        public static string Inv_Detail_AvailableQtyLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_AvailableQtyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ID:.
        /// </summary>
        public static string Inv_Detail_ItemIDLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_ItemIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type:.
        /// </summary>
        public static string Inv_Detail_ItemTypeLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_ItemTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Restocked:.
        /// </summary>
        public static string Inv_Detail_LastRestockedLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_LastRestockedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Stock Threshold:.
        /// </summary>
        public static string Inv_Detail_LowThresholdLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_LowThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string Inv_Detail_NoteLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Quantity:.
        /// </summary>
        public static string Inv_Detail_UsedQtyLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_UsedQtyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No inventory items found.
        /// </summary>
        public static string Inv_EmptyState {
            get {
                return ResourceManager.GetString("Inv_EmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ New Item.
        /// </summary>
        public static string Inv_NewItem {
            get {
                return ResourceManager.GetString("Inv_NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by item type.
        /// </summary>
        public static string Inv_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Inv_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string InvDet_Available {
            get {
                return ResourceManager.GetString("InvDet_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✖ Close.
        /// </summary>
        public static string InvDet_Close {
            get {
                return ResourceManager.GetString("InvDet_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string InvDet_ItemType {
            get {
                return ResourceManager.GetString("InvDet_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Restocked.
        /// </summary>
        public static string InvDet_LastRestocked {
            get {
                return ResourceManager.GetString("InvDet_LastRestocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Used.
        /// </summary>
        public static string InvDet_LastUsed {
            get {
                return ResourceManager.GetString("InvDet_LastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is low on stock..
        /// </summary>
        public static string InvDet_LowStockMsg {
            get {
                return ResourceManager.GetString("InvDet_LowStockMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string InvDet_Note {
            get {
                return ResourceManager.GetString("InvDet_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restocked By.
        /// </summary>
        public static string InvDet_Restock_By {
            get {
                return ResourceManager.GetString("InvDet_Restock_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string InvDet_Restock_Note {
            get {
                return ResourceManager.GetString("InvDet_Restock_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string InvDet_Restock_Qty {
            get {
                return ResourceManager.GetString("InvDet_Restock_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string InvDet_Restock_When {
            get {
                return ResourceManager.GetString("InvDet_Restock_When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restock History.
        /// </summary>
        public static string InvDet_RestockHistory {
            get {
                return ResourceManager.GetString("InvDet_RestockHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Stock.
        /// </summary>
        public static string InvDet_Status_InStock {
            get {
                return ResourceManager.GetString("InvDet_Status_InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Details.
        /// </summary>
        public static string InvDet_Title {
            get {
                return ResourceManager.GetString("InvDet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household.
        /// </summary>
        public static string InvDet_Usage_Household {
            get {
                return ResourceManager.GetString("InvDet_Usage_Household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Used.
        /// </summary>
        public static string InvDet_Usage_QtyUsed {
            get {
                return ResourceManager.GetString("InvDet_Usage_QtyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string InvDet_Usage_Service {
            get {
                return ResourceManager.GetString("InvDet_Usage_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician(s).
        /// </summary>
        public static string InvDet_Usage_Technicians {
            get {
                return ResourceManager.GetString("InvDet_Usage_Technicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used By.
        /// </summary>
        public static string InvDet_Usage_UsedBy {
            get {
                return ResourceManager.GetString("InvDet_Usage_UsedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string InvDet_Usage_When {
            get {
                return ResourceManager.GetString("InvDet_Usage_When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage History.
        /// </summary>
        public static string InvDet_UsageHistory {
            get {
                return ResourceManager.GetString("InvDet_UsageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string InvDet_Used {
            get {
                return ResourceManager.GetString("InvDet_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✖ Cancel.
        /// </summary>
        public static string ItemDlg_Cancel {
            get {
                return ResourceManager.GetString("ItemDlg_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string ItemDlg_Note {
            get {
                return ResourceManager.GetString("ItemDlg_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✔ OK.
        /// </summary>
        public static string ItemDlg_OK {
            get {
                return ResourceManager.GetString("ItemDlg_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string ItemDlg_Person {
            get {
                return ResourceManager.GetString("ItemDlg_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string ItemDlg_Quantity {
            get {
                return ResourceManager.GetString("ItemDlg_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ItemDlg_Title {
            get {
                return ResourceManager.GetString("ItemDlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Login_Button_Exit {
            get {
                return ResourceManager.GetString("Login_Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Button_Login {
            get {
                return ResourceManager.GetString("Login_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New User.
        /// </summary>
        public static string Login_Button_RegisterNewUser {
            get {
                return ResourceManager.GetString("Login_Button_RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back.
        /// </summary>
        public static string Login_Welcome {
            get {
                return ResourceManager.GetString("Login_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔌 Blue Smart Charger.
        /// </summary>
        public static string Menu_BlueSmartCharger {
            get {
                return ResourceManager.GetString("Menu_BlueSmartCharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧭 Controller Test.
        /// </summary>
        public static string Menu_ControllerTest {
            get {
                return ResourceManager.GetString("Menu_ControllerTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚡Electronic Load.
        /// </summary>
        public static string Menu_ElectronicLoad {
            get {
                return ResourceManager.GetString("Menu_ElectronicLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📦 Inventory.
        /// </summary>
        public static string Menu_Inventory {
            get {
                return ResourceManager.GetString("Menu_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👥 Manage Users.
        /// </summary>
        public static string Menu_ManageUsers {
            get {
                return ResourceManager.GetString("Menu_ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔋 MPPT Monitoring.
        /// </summary>
        public static string Menu_MpptMonitoring {
            get {
                return ResourceManager.GetString("Menu_MpptMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📊 Multimeter.
        /// </summary>
        public static string Menu_Multimeter {
            get {
                return ResourceManager.GetString("Menu_Multimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📈 Oscilloscope.
        /// </summary>
        public static string Menu_Oscilloscope {
            get {
                return ResourceManager.GetString("Menu_Oscilloscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛠 Service Records.
        /// </summary>
        public static string Menu_ServiceRecords {
            get {
                return ResourceManager.GetString("Menu_ServiceRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏠 Sites.
        /// </summary>
        public static string Menu_Sites {
            get {
                return ResourceManager.GetString("Menu_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔀 Switch Test.
        /// </summary>
        public static string Menu_SwitchTest {
            get {
                return ResourceManager.GetString("Menu_SwitchTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📁 Templates.
        /// </summary>
        public static string Menu_Templates {
            get {
                return ResourceManager.GetString("Menu_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestProcedure.
        /// </summary>
        public static string Menu_TestProcedure {
            get {
                return ResourceManager.GetString("Menu_TestProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 Test Reports.
        /// </summary>
        public static string Menu_TestReports {
            get {
                return ResourceManager.GetString("Menu_TestReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Instruments.
        /// </summary>
        public static string Monitoring_LiveInstruments {
            get {
                return ResourceManager.GetString("Monitoring_LiveInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Nav_Logout {
            get {
                return ResourceManager.GetString("Nav_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙ Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string OHV_Column_Comment {
            get {
                return ResourceManager.GetString("OHV_Column_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string OHV_Column_Contact {
            get {
                return ResourceManager.GetString("OHV_Column_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string OHV_Column_District {
            get {
                return ResourceManager.GetString("OHV_Column_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string OHV_Column_ID {
            get {
                return ResourceManager.GetString("OHV_Column_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string OHV_Column_Installed {
            get {
                return ResourceManager.GetString("OHV_Column_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Inspect.
        /// </summary>
        public static string OHV_Column_LastInspect {
            get {
                return ResourceManager.GetString("OHV_Column_LastInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        public static string OHV_Column_Municipality {
            get {
                return ResourceManager.GetString("OHV_Column_Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string OHV_Column_OwnerName {
            get {
                return ResourceManager.GetString("OHV_Column_OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string OHV_Column_Status {
            get {
                return ResourceManager.GetString("OHV_Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string OHV_Column_UserName {
            get {
                return ResourceManager.GetString("OHV_Column_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operational households found.
        /// </summary>
        public static string OHV_EmptyState {
            get {
                return ResourceManager.GetString("OHV_EmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by owner, user, area or contact.
        /// </summary>
        public static string OHV_SearchPlaceholder {
            get {
                return ResourceManager.GetString("OHV_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status (read-only in this view).
        /// </summary>
        public static string OHV_Status_Tooltip {
            get {
                return ResourceManager.GetString("OHV_Status_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string OOSV_Column_Comment {
            get {
                return ResourceManager.GetString("OOSV_Column_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string OOSV_Column_Contact {
            get {
                return ResourceManager.GetString("OOSV_Column_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string OOSV_Column_District {
            get {
                return ResourceManager.GetString("OOSV_Column_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string OOSV_Column_ID {
            get {
                return ResourceManager.GetString("OOSV_Column_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string OOSV_Column_Installed {
            get {
                return ResourceManager.GetString("OOSV_Column_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Inspect.
        /// </summary>
        public static string OOSV_Column_LastInspect {
            get {
                return ResourceManager.GetString("OOSV_Column_LastInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        public static string OOSV_Column_Municipality {
            get {
                return ResourceManager.GetString("OOSV_Column_Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string OOSV_Column_OwnerName {
            get {
                return ResourceManager.GetString("OOSV_Column_OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string OOSV_Column_Status {
            get {
                return ResourceManager.GetString("OOSV_Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string OOSV_Column_UserName {
            get {
                return ResourceManager.GetString("OOSV_Column_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No out-of-service households found.
        /// </summary>
        public static string OOSV_EmptyState {
            get {
                return ResourceManager.GetString("OOSV_EmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by owner, user, area or contact.
        /// </summary>
        public static string OOSV_SearchPlaceholder {
            get {
                return ResourceManager.GetString("OOSV_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to change status (Admins only).
        /// </summary>
        public static string OOSV_Status_Tooltip {
            get {
                return ResourceManager.GetString("OOSV_Status_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (required for technician).
        /// </summary>
        public static string Register_AddressLabel {
            get {
                return ResourceManager.GetString("Register_AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Area (required for technician).
        /// </summary>
        public static string Register_AreaLabel {
            get {
                return ResourceManager.GetString("Register_AreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Login.
        /// </summary>
        public static string Register_Button_BackToLogin {
            get {
                return ResourceManager.GetString("Register_Button_BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Button_Register {
            get {
                return ResourceManager.GetString("Register_Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("Register_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Register_Name {
            get {
                return ResourceManager.GetString("Register_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note (optional).
        /// </summary>
        public static string Register_NoteLabel {
            get {
                return ResourceManager.GetString("Register_NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be longer than 6 characters and include at least one number or symbol. It cannot be the same as your Name or Username..
        /// </summary>
        public static string Register_PasswordNote {
            get {
                return ResourceManager.GetString("Register_PasswordNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone (digits only, 8–15).
        /// </summary>
        public static string Register_PhoneLabel {
            get {
                return ResourceManager.GetString("Register_PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a technician (request approval).
        /// </summary>
        public static string Register_TechToggle {
            get {
                return ResourceManager.GetString("Register_TechToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Account.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Register_Username {
            get {
                return ResourceManager.GetString("Register_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Role_Admin {
            get {
                return ResourceManager.GetString("Role_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Role_Guest {
            get {
                return ResourceManager.GetString("Role_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string Role_Technician {
            get {
                return ResourceManager.GetString("Role_Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📊 Dashboard.
        /// </summary>
        public static string Section_Dashboard {
            get {
                return ResourceManager.GetString("Section_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛰 Monitoring.
        /// </summary>
        public static string Section_Monitoring {
            get {
                return ResourceManager.GetString("Section_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧪 Test Manuals.
        /// </summary>
        public static string Section_TestManuals {
            get {
                return ResourceManager.GetString("Section_TestManuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≡ Main Menu.
        /// </summary>
        public static string Sidebar_MainMenu {
            get {
                return ResourceManager.GetString("Sidebar_MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string SR_Column_Action {
            get {
                return ResourceManager.GetString("SR_Column_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string SR_Column_Finish {
            get {
                return ResourceManager.GetString("SR_Column_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household.
        /// </summary>
        public static string SR_Column_Household {
            get {
                return ResourceManager.GetString("SR_Column_Household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string SR_Column_ID {
            get {
                return ResourceManager.GetString("SR_Column_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inv. Used.
        /// </summary>
        public static string SR_Column_InventoryUsed {
            get {
                return ResourceManager.GetString("SR_Column_InventoryUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        public static string SR_Column_Problem {
            get {
                return ResourceManager.GetString("SR_Column_Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string SR_Column_Start {
            get {
                return ResourceManager.GetString("SR_Column_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SR_Column_Status {
            get {
                return ResourceManager.GetString("SR_Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technicians.
        /// </summary>
        public static string SR_Column_Technicians {
            get {
                return ResourceManager.GetString("SR_Column_Technicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:.
        /// </summary>
        public static string SR_Detail_Action {
            get {
                return ResourceManager.GetString("SR_Detail_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished:.
        /// </summary>
        public static string SR_Detail_Finished {
            get {
                return ResourceManager.GetString("SR_Detail_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household:.
        /// </summary>
        public static string SR_Detail_Household {
            get {
                return ResourceManager.GetString("SR_Detail_Household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Used:.
        /// </summary>
        public static string SR_Detail_InventoryUsed {
            get {
                return ResourceManager.GetString("SR_Detail_InventoryUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Tech:.
        /// </summary>
        public static string SR_Detail_PrimaryTech {
            get {
                return ResourceManager.GetString("SR_Detail_PrimaryTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem:.
        /// </summary>
        public static string SR_Detail_Problem {
            get {
                return ResourceManager.GetString("SR_Detail_Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service ID:.
        /// </summary>
        public static string SR_Detail_ServiceID {
            get {
                return ResourceManager.GetString("SR_Detail_ServiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started:.
        /// </summary>
        public static string SR_Detail_Started {
            get {
                return ResourceManager.GetString("SR_Detail_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string SR_Detail_Status {
            get {
                return ResourceManager.GetString("SR_Detail_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team:.
        /// </summary>
        public static string SR_Detail_Team {
            get {
                return ResourceManager.GetString("SR_Detail_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service records found.
        /// </summary>
        public static string SR_EmptyState {
            get {
                return ResourceManager.GetString("SR_EmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by household/tech/problem/action/status.
        /// </summary>
        public static string SR_SearchPlaceholder {
            get {
                return ResourceManager.GetString("SR_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Status_Admin {
            get {
                return ResourceManager.GetString("Status_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Status_Approved {
            get {
                return ResourceManager.GetString("Status_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blocked.
        /// </summary>
        public static string Status_Blocked {
            get {
                return ResourceManager.GetString("Status_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string Status_Declined {
            get {
                return ResourceManager.GetString("Status_Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inactive.
        /// </summary>
        public static string Status_Inactive {
            get {
                return ResourceManager.GetString("Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Status_Pending {
            get {
                return ResourceManager.GetString("Status_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Status_User {
            get {
                return ResourceManager.GetString("Status_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Dashboard.
        /// </summary>
        public static string SV_BackToDashboard {
            get {
                return ResourceManager.GetString("SV_BackToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Dashboard (Alt+Left).
        /// </summary>
        public static string SV_BackToDashboard_Tooltip {
            get {
                return ResourceManager.GetString("SV_BackToDashboard_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string SV_Breadcrumb_Dashboard {
            get {
                return ResourceManager.GetString("SV_Breadcrumb_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Dashboard.
        /// </summary>
        public static string SV_Breadcrumb_Dashboard_Tooltip {
            get {
                return ResourceManager.GetString("SV_Breadcrumb_Dashboard_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites.
        /// </summary>
        public static string SV_Breadcrumb_Sites {
            get {
                return ResourceManager.GetString("SV_Breadcrumb_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a tile to show details here….
        /// </summary>
        public static string SV_Placeholder {
            get {
                return ResourceManager.GetString("SV_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational.
        /// </summary>
        public static string SV_Tile_Operational {
            get {
                return ResourceManager.GetString("SV_Tile_Operational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Service.
        /// </summary>
        public static string SV_Tile_OutOfService {
            get {
                return ResourceManager.GetString("SV_Tile_OutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Households.
        /// </summary>
        public static string SV_Tile_TotalHouseholds {
            get {
                return ResourceManager.GetString("SV_Tile_TotalHouseholds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites.
        /// </summary>
        public static string SV_Title {
            get {
                return ResourceManager.GetString("SV_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string TestManuals_Documentation {
            get {
                return ResourceManager.GetString("TestManuals_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Modules.
        /// </summary>
        public static string TestManuals_TestModules {
            get {
                return ResourceManager.GetString("TestManuals_TestModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Add User.
        /// </summary>
        public static string UM_AddUser {
            get {
                return ResourceManager.GetString("UM_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string UM_Approve {
            get {
                return ResourceManager.GetString("UM_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string UM_Column_Address {
            get {
                return ResourceManager.GetString("UM_Column_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string UM_Column_Approval {
            get {
                return ResourceManager.GetString("UM_Column_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Area.
        /// </summary>
        public static string UM_Column_AssignedArea {
            get {
                return ResourceManager.GetString("UM_Column_AssignedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string UM_Column_ID {
            get {
                return ResourceManager.GetString("UM_Column_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UM_Column_Name {
            get {
                return ResourceManager.GetString("UM_Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string UM_Column_Note {
            get {
                return ResourceManager.GetString("UM_Column_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string UM_Column_Phone {
            get {
                return ResourceManager.GetString("UM_Column_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string UM_Column_Role {
            get {
                return ResourceManager.GetString("UM_Column_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string UM_Column_Status {
            get {
                return ResourceManager.GetString("UM_Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UM_Column_Username {
            get {
                return ResourceManager.GetString("UM_Column_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string UM_Context_Admin {
            get {
                return ResourceManager.GetString("UM_Context_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change role.
        /// </summary>
        public static string UM_Context_ChangeRole {
            get {
                return ResourceManager.GetString("UM_Context_ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        public static string UM_Context_DeleteUser {
            get {
                return ResourceManager.GetString("UM_Context_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string UM_Context_Guest {
            get {
                return ResourceManager.GetString("UM_Context_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string UM_Context_Technician {
            get {
                return ResourceManager.GetString("UM_Context_Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string UM_Decline {
            get {
                return ResourceManager.GetString("UM_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users found.
        /// </summary>
        public static string UM_EmptyState {
            get {
                return ResourceManager.GetString("UM_EmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search name/username/role/phone/address/area/note/status.
        /// </summary>
        public static string UM_SearchPlaceholder {
            get {
                return ResourceManager.GetString("UM_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👥 User Management.
        /// </summary>
        public static string UM_Title {
            get {
                return ResourceManager.GetString("UM_Title", resourceCulture);
            }
        }
    }
}
