//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseholdMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HouseholdMS.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV Testing Workbench.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Sections.
        /// </summary>
        public static string Dashboard_Sections {
            get {
                return ResourceManager.GetString("Dashboard_Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restock.
        /// </summary>
        public static string Inv_Action_Restock {
            get {
                return ResourceManager.GetString("Inv_Action_Restock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Inv_Action_Use {
            get {
                return ResourceManager.GetString("Inv_Action_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Qty.
        /// </summary>
        public static string Inv_Column_AvailableQty {
            get {
                return ResourceManager.GetString("Inv_Column_AvailableQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Inv_Column_ID {
            get {
                return ResourceManager.GetString("Inv_Column_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string Inv_Column_ItemType {
            get {
                return ResourceManager.GetString("Inv_Column_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Restocked.
        /// </summary>
        public static string Inv_Column_LastRestocked {
            get {
                return ResourceManager.GetString("Inv_Column_LastRestocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Threshold.
        /// </summary>
        public static string Inv_Column_LowThreshold {
            get {
                return ResourceManager.GetString("Inv_Column_LowThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Inv_Column_Note {
            get {
                return ResourceManager.GetString("Inv_Column_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Qty.
        /// </summary>
        public static string Inv_Column_UsedQty {
            get {
                return ResourceManager.GetString("Inv_Column_UsedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Quantity:.
        /// </summary>
        public static string Inv_Detail_AvailableQtyLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_AvailableQtyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ID:.
        /// </summary>
        public static string Inv_Detail_ItemIDLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_ItemIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type:.
        /// </summary>
        public static string Inv_Detail_ItemTypeLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_ItemTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Restocked:.
        /// </summary>
        public static string Inv_Detail_LastRestockedLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_LastRestockedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Stock Threshold:.
        /// </summary>
        public static string Inv_Detail_LowThresholdLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_LowThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string Inv_Detail_NoteLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Quantity:.
        /// </summary>
        public static string Inv_Detail_UsedQtyLabel {
            get {
                return ResourceManager.GetString("Inv_Detail_UsedQtyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No inventory items found.
        /// </summary>
        public static string Inv_EmptyState {
            get {
                return ResourceManager.GetString("Inv_EmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ New Item.
        /// </summary>
        public static string Inv_NewItem {
            get {
                return ResourceManager.GetString("Inv_NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by item type.
        /// </summary>
        public static string Inv_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Inv_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✖ Cancel.
        /// </summary>
        public static string ItemDlg_Cancel {
            get {
                return ResourceManager.GetString("ItemDlg_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string ItemDlg_Note {
            get {
                return ResourceManager.GetString("ItemDlg_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✔ OK.
        /// </summary>
        public static string ItemDlg_OK {
            get {
                return ResourceManager.GetString("ItemDlg_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string ItemDlg_Person {
            get {
                return ResourceManager.GetString("ItemDlg_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string ItemDlg_Quantity {
            get {
                return ResourceManager.GetString("ItemDlg_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ItemDlg_Title {
            get {
                return ResourceManager.GetString("ItemDlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Login_Button_Exit {
            get {
                return ResourceManager.GetString("Login_Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Button_Login {
            get {
                return ResourceManager.GetString("Login_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New User.
        /// </summary>
        public static string Login_Button_RegisterNewUser {
            get {
                return ResourceManager.GetString("Login_Button_RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back.
        /// </summary>
        public static string Login_Welcome {
            get {
                return ResourceManager.GetString("Login_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔌 Blue Smart Charger.
        /// </summary>
        public static string Menu_BlueSmartCharger {
            get {
                return ResourceManager.GetString("Menu_BlueSmartCharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧭 Controller Test.
        /// </summary>
        public static string Menu_ControllerTest {
            get {
                return ResourceManager.GetString("Menu_ControllerTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚡Electronic Load.
        /// </summary>
        public static string Menu_ElectronicLoad {
            get {
                return ResourceManager.GetString("Menu_ElectronicLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📦 Inventory.
        /// </summary>
        public static string Menu_Inventory {
            get {
                return ResourceManager.GetString("Menu_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👥 Manage Users.
        /// </summary>
        public static string Menu_ManageUsers {
            get {
                return ResourceManager.GetString("Menu_ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔋 MPPT Monitoring.
        /// </summary>
        public static string Menu_MpptMonitoring {
            get {
                return ResourceManager.GetString("Menu_MpptMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📊 Multimeter.
        /// </summary>
        public static string Menu_Multimeter {
            get {
                return ResourceManager.GetString("Menu_Multimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📈 Oscilloscope.
        /// </summary>
        public static string Menu_Oscilloscope {
            get {
                return ResourceManager.GetString("Menu_Oscilloscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛠 Service Records.
        /// </summary>
        public static string Menu_ServiceRecords {
            get {
                return ResourceManager.GetString("Menu_ServiceRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏠 Sites.
        /// </summary>
        public static string Menu_Sites {
            get {
                return ResourceManager.GetString("Menu_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔀 Switch Test.
        /// </summary>
        public static string Menu_SwitchTest {
            get {
                return ResourceManager.GetString("Menu_SwitchTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📁 Templates.
        /// </summary>
        public static string Menu_Templates {
            get {
                return ResourceManager.GetString("Menu_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestProcedure.
        /// </summary>
        public static string Menu_TestProcedure {
            get {
                return ResourceManager.GetString("Menu_TestProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 Test Reports.
        /// </summary>
        public static string Menu_TestReports {
            get {
                return ResourceManager.GetString("Menu_TestReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Instruments.
        /// </summary>
        public static string Monitoring_LiveInstruments {
            get {
                return ResourceManager.GetString("Monitoring_LiveInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Nav_Logout {
            get {
                return ResourceManager.GetString("Nav_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙ Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (required for technician).
        /// </summary>
        public static string Register_AddressLabel {
            get {
                return ResourceManager.GetString("Register_AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Area (required for technician).
        /// </summary>
        public static string Register_AreaLabel {
            get {
                return ResourceManager.GetString("Register_AreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Login.
        /// </summary>
        public static string Register_Button_BackToLogin {
            get {
                return ResourceManager.GetString("Register_Button_BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Button_Register {
            get {
                return ResourceManager.GetString("Register_Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("Register_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Register_Name {
            get {
                return ResourceManager.GetString("Register_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note (optional).
        /// </summary>
        public static string Register_NoteLabel {
            get {
                return ResourceManager.GetString("Register_NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be longer than 6 characters and include at least one number or symbol. It cannot be the same as your Name or Username..
        /// </summary>
        public static string Register_PasswordNote {
            get {
                return ResourceManager.GetString("Register_PasswordNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone (digits only, 8–15).
        /// </summary>
        public static string Register_PhoneLabel {
            get {
                return ResourceManager.GetString("Register_PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a technician (request approval).
        /// </summary>
        public static string Register_TechToggle {
            get {
                return ResourceManager.GetString("Register_TechToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Account.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Register_Username {
            get {
                return ResourceManager.GetString("Register_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Role_Admin {
            get {
                return ResourceManager.GetString("Role_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Role_Guest {
            get {
                return ResourceManager.GetString("Role_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string Role_Technician {
            get {
                return ResourceManager.GetString("Role_Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📊 Dashboard.
        /// </summary>
        public static string Section_Dashboard {
            get {
                return ResourceManager.GetString("Section_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛰 Monitoring.
        /// </summary>
        public static string Section_Monitoring {
            get {
                return ResourceManager.GetString("Section_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧪 Test Manuals.
        /// </summary>
        public static string Section_TestManuals {
            get {
                return ResourceManager.GetString("Section_TestManuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≡ Main Menu.
        /// </summary>
        public static string Sidebar_MainMenu {
            get {
                return ResourceManager.GetString("Sidebar_MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Status_Admin {
            get {
                return ResourceManager.GetString("Status_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Status_Approved {
            get {
                return ResourceManager.GetString("Status_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blocked.
        /// </summary>
        public static string Status_Blocked {
            get {
                return ResourceManager.GetString("Status_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string Status_Declined {
            get {
                return ResourceManager.GetString("Status_Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inactive.
        /// </summary>
        public static string Status_Inactive {
            get {
                return ResourceManager.GetString("Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Status_Pending {
            get {
                return ResourceManager.GetString("Status_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Status_User {
            get {
                return ResourceManager.GetString("Status_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string TestManuals_Documentation {
            get {
                return ResourceManager.GetString("TestManuals_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Modules.
        /// </summary>
        public static string TestManuals_TestModules {
            get {
                return ResourceManager.GetString("TestManuals_TestModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Add User.
        /// </summary>
        public static string UM_AddUser {
            get {
                return ResourceManager.GetString("UM_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string UM_Approve {
            get {
                return ResourceManager.GetString("UM_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string UM_Column_Address {
            get {
                return ResourceManager.GetString("UM_Column_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string UM_Column_Approval {
            get {
                return ResourceManager.GetString("UM_Column_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Area.
        /// </summary>
        public static string UM_Column_AssignedArea {
            get {
                return ResourceManager.GetString("UM_Column_AssignedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string UM_Column_ID {
            get {
                return ResourceManager.GetString("UM_Column_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UM_Column_Name {
            get {
                return ResourceManager.GetString("UM_Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string UM_Column_Note {
            get {
                return ResourceManager.GetString("UM_Column_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string UM_Column_Phone {
            get {
                return ResourceManager.GetString("UM_Column_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string UM_Column_Role {
            get {
                return ResourceManager.GetString("UM_Column_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string UM_Column_Status {
            get {
                return ResourceManager.GetString("UM_Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UM_Column_Username {
            get {
                return ResourceManager.GetString("UM_Column_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string UM_Context_Admin {
            get {
                return ResourceManager.GetString("UM_Context_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change role.
        /// </summary>
        public static string UM_Context_ChangeRole {
            get {
                return ResourceManager.GetString("UM_Context_ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        public static string UM_Context_DeleteUser {
            get {
                return ResourceManager.GetString("UM_Context_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string UM_Context_Guest {
            get {
                return ResourceManager.GetString("UM_Context_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string UM_Context_Technician {
            get {
                return ResourceManager.GetString("UM_Context_Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string UM_Decline {
            get {
                return ResourceManager.GetString("UM_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users found.
        /// </summary>
        public static string UM_EmptyState {
            get {
                return ResourceManager.GetString("UM_EmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search name/username/role/phone/address/area/note/status.
        /// </summary>
        public static string UM_SearchPlaceholder {
            get {
                return ResourceManager.GetString("UM_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👥 User Management.
        /// </summary>
        public static string UM_Title {
            get {
                return ResourceManager.GetString("UM_Title", resourceCulture);
            }
        }
    }
}
